config/routes.rb
Timer::Application.routes.draw do
  get "welcome/index"
  resources :competitions

   root 'welcome#index'

end

app/models/competition.rb
class Competition < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: [:show, :edit, :update, :destroy]

  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(competition_params)

    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render action: 'show', status: :created, location: @competition }
      else
        format.html { render action: 'new' }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1
  # PATCH/PUT /competitions/1.json
  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_params
      params.require(:competition).permit(:prize, :Date)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/competitions/_form.html.erb
<%= form_for(@competition) do |f| %>
  <% if @competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
      <% @competition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :prize %><br>
    <%= f.text_field :prize %>
  </div>
  <div class="field">
    <%= f.label :Date %><br>
    <%= f.date_select :Date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/competitions/edit.html.erb
<h1>Editing competition</h1>

<%= render 'form' %>

<%= link_to 'Show', @competition %> |
<%= link_to 'Back', competitions_path %>

app/views/competitions/index.html.erb
<h1>Listing competitions</h1>

<table>
  <thead>
    <tr>
      <th>Prize</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @competitions.each do |competition| %>
      <tr>
        <td><%= competition.prize %></td>
        <td><%= competition.Date %></td>
        <td><%= link_to 'Show', competition %></td>
        <td><%= link_to 'Edit', edit_competition_path(competition) %></td>
        <td><%= link_to 'Destroy', competition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Competition', new_competition_path %>

app/views/competitions/new.html.erb
<h1>New competition</h1>

<%= render 'form' %>

<%= link_to 'Back', competitions_path %>

app/views/competitions/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Prize:</strong>
  <%= @competition.prize %>
</p>
<p>
  <strong>Date:</strong>
  <%= @competition.Date %>
</p>
<%= link_to 'Edit', edit_competition_path(@competition) %> |
<%= link_to 'Back', competitions_path %>
<h1>Timer</h1>

<div id="until2d"></div>
$('#until2d').countdown({until: '+2d'});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- you don't need this here because these things are included in your application.js and application.css by the asset pipeline 

Read more about the asset pipeline and the above javascript_include_tag and stylesheet_include_tag helpers


<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="css/jquery.countdown.css"> 
<script type="text/javascript" src="js/jquery.plugin.js"></script> 
<script type="text/javascript" src="js/jquery.countdown.js"></script>

-->

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>